# Generated by Django 5.1.1 on 2024-10-05 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_actual_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlisted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
